// <auto-generated />
using System;
using Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211004190948_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Api.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNo")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNo = "GR32882957347263523",
                            Amount = 5000.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 73, DateTimeKind.Local).AddTicks(8154),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountNo = "GR00324783252634532",
                            Amount = 18500.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4870),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountNo = "GR12309848325265443",
                            Amount = 25450.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4894),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            AccountNo = "GR12309845325290065",
                            Amount = 13670.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4898),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            AccountNo = "GR16632489265422345",
                            Amount = 72344.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4900),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            AccountNo = "GR72347888234265443",
                            Amount = 2114.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4903),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            AccountNo = "GR32882957367263523",
                            Amount = 5000.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4905),
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            AccountNo = "GR00324783252634032",
                            Amount = 18500.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4907),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            AccountNo = "GR12309845325265443",
                            Amount = 25450.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4909),
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            AccountNo = "GR12339845325290065",
                            Amount = 13670.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4911),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            AccountNo = "GR16632489265422345",
                            Amount = 72344.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4913),
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            AccountNo = "GR72347888234265443",
                            Amount = 2114.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4916),
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            AccountNo = "GR32882957747263523",
                            Amount = 5000.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4918),
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            AccountNo = "GR00324783252631532",
                            Amount = 18500.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4920),
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            AccountNo = "GR12309845325265443",
                            Amount = 25450.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4922),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            AccountNo = "GR12309845329290065",
                            Amount = 13670.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4924),
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            AccountNo = "GR16632489265422345",
                            Amount = 72344.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4926),
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            AccountNo = "GR72347888234265443",
                            Amount = 2114.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4928),
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            AccountNo = "GR32882957387263523",
                            Amount = 5000.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4930),
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            AccountNo = "GR01324783252634532",
                            Amount = 18500.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4932),
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            AccountNo = "GR12309845325265443",
                            Amount = 25450.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4934),
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            AccountNo = "GR12309845305290065",
                            Amount = 13670.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4936),
                            UserId = 1
                        },
                        new
                        {
                            Id = 23,
                            AccountNo = "GR16632489265422345",
                            Amount = 72344.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4939),
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            AccountNo = "GR72347888234265443",
                            Amount = 2114.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4941),
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            AccountNo = "GR32882957347293523",
                            Amount = 5000.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4943),
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            AccountNo = "GR00774783252634532",
                            Amount = 18500.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4945),
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            AccountNo = "GR12309845325265443",
                            Amount = 25450.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4947),
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            AccountNo = "GR12309840025290065",
                            Amount = 13670.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4950),
                            UserId = 1
                        },
                        new
                        {
                            Id = 29,
                            AccountNo = "GR16632489265422345",
                            Amount = 72344.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4952),
                            UserId = 1
                        },
                        new
                        {
                            Id = 30,
                            AccountNo = "GR72347888234265443",
                            Amount = 2114.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4954),
                            UserId = 1
                        },
                        new
                        {
                            Id = 31,
                            AccountNo = "GR32882957347063523",
                            Amount = 5000.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4956),
                            UserId = 1
                        },
                        new
                        {
                            Id = 32,
                            AccountNo = "GR00324783992634532",
                            Amount = 18500.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4958),
                            UserId = 1
                        },
                        new
                        {
                            Id = 33,
                            AccountNo = "GR12309845325265443",
                            Amount = 25450.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4960),
                            UserId = 1
                        },
                        new
                        {
                            Id = 34,
                            AccountNo = "GR12309845005290065",
                            Amount = 13670.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4963),
                            UserId = 1
                        },
                        new
                        {
                            Id = 35,
                            AccountNo = "GR16632489265422345",
                            Amount = 72344.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4965),
                            UserId = 1
                        },
                        new
                        {
                            Id = 36,
                            AccountNo = "GR72347888234265443",
                            Amount = 2114.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4967),
                            UserId = 1
                        },
                        new
                        {
                            Id = 37,
                            AccountNo = "GR32882957227263523",
                            Amount = 5000.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4969),
                            UserId = 1
                        },
                        new
                        {
                            Id = 38,
                            AccountNo = "GR00324711152634532",
                            Amount = 18500.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4971),
                            UserId = 1
                        },
                        new
                        {
                            Id = 39,
                            AccountNo = "GR12309845325265443",
                            Amount = 25450.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4973),
                            UserId = 1
                        },
                        new
                        {
                            Id = 40,
                            AccountNo = "GR12309845325299065",
                            Amount = 13670.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4975),
                            UserId = 1
                        },
                        new
                        {
                            Id = 41,
                            AccountNo = "GR16632489222422345",
                            Amount = 72344.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4977),
                            UserId = 1
                        },
                        new
                        {
                            Id = 42,
                            AccountNo = "GR72347888234265443",
                            Amount = 2114.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4979),
                            UserId = 1
                        },
                        new
                        {
                            Id = 43,
                            AccountNo = "GR32882957457263523",
                            Amount = 5000.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4981),
                            UserId = 1
                        },
                        new
                        {
                            Id = 44,
                            AccountNo = "GR00324443252634532",
                            Amount = 18500.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4984),
                            UserId = 1
                        },
                        new
                        {
                            Id = 45,
                            AccountNo = "GR12309845325265400",
                            Amount = 25450.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4986),
                            UserId = 1
                        },
                        new
                        {
                            Id = 46,
                            AccountNo = "GR12309845325200065",
                            Amount = 13670.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4988),
                            UserId = 1
                        },
                        new
                        {
                            Id = 47,
                            AccountNo = "GR16632489765422345",
                            Amount = 72344.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4990),
                            UserId = 1
                        },
                        new
                        {
                            Id = 48,
                            AccountNo = "GR72347888234865443",
                            Amount = 2114.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4992),
                            UserId = 1
                        },
                        new
                        {
                            Id = 49,
                            AccountNo = "GR32882988347263523",
                            Amount = 5000.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4994),
                            UserId = 1
                        },
                        new
                        {
                            Id = 50,
                            AccountNo = "GR00324788852634532",
                            Amount = 18500.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4996),
                            UserId = 1
                        },
                        new
                        {
                            Id = 51,
                            AccountNo = "GR12309845885265443",
                            Amount = 25450.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(4998),
                            UserId = 1
                        },
                        new
                        {
                            Id = 52,
                            AccountNo = "GR12309845388290065",
                            Amount = 13670.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(5001),
                            UserId = 1
                        },
                        new
                        {
                            Id = 53,
                            AccountNo = "GR16632489265882345",
                            Amount = 72344.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(5003),
                            UserId = 1
                        },
                        new
                        {
                            Id = 54,
                            AccountNo = "GR72347888234265443",
                            Amount = 2114.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(5005),
                            UserId = 1
                        },
                        new
                        {
                            Id = 55,
                            AccountNo = "GR32882957388263523",
                            Amount = 5000.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(5007),
                            UserId = 1
                        },
                        new
                        {
                            Id = 56,
                            AccountNo = "GR00324783252004532",
                            Amount = 18500.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(5009),
                            UserId = 1
                        },
                        new
                        {
                            Id = 57,
                            AccountNo = "GR12309845112265443",
                            Amount = 25450.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(5011),
                            UserId = 1
                        },
                        new
                        {
                            Id = 58,
                            AccountNo = "GR12309811325290065",
                            Amount = 13670.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(5013),
                            UserId = 1
                        },
                        new
                        {
                            Id = 59,
                            AccountNo = "GR16632489261122345",
                            Amount = 72344.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(5015),
                            UserId = 1
                        },
                        new
                        {
                            Id = 60,
                            AccountNo = "GR72347888237765464",
                            Amount = 2114.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(5017),
                            UserId = 1
                        },
                        new
                        {
                            Id = 61,
                            AccountNo = "GR12309845325265492",
                            Amount = 25450.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(5019),
                            UserId = 1
                        },
                        new
                        {
                            Id = 62,
                            AccountNo = "GR12309845325290023",
                            Amount = 13670.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(5021),
                            UserId = 1
                        },
                        new
                        {
                            Id = 63,
                            AccountNo = "GR16632489265422388",
                            Amount = 72344.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(5023),
                            UserId = 1
                        },
                        new
                        {
                            Id = 64,
                            AccountNo = "GR72347888234265464",
                            Amount = 2114.0,
                            CreatedAt = new DateTime(2021, 10, 4, 22, 9, 48, 75, DateTimeKind.Local).AddTicks(5068),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 226, 90, 232, 54, 15, 6, 114, 129, 161, 32, 104, 61, 224, 76, 207, 152, 165, 105, 171, 13, 239, 211, 81, 105, 90, 14, 39, 48, 253, 63, 61, 22, 180, 147, 39, 138, 237, 101, 132, 180, 111, 162, 149, 115, 178, 219, 72, 166, 37, 97, 88, 226, 216, 71, 122, 196, 89, 198, 182, 162, 122, 193, 72, 237 },
                            PasswordSalt = new byte[] { 252, 5, 161, 178, 112, 65, 74, 254, 180, 194, 253, 132, 160, 134, 118, 228, 124, 233, 190, 240, 207, 75, 132, 6, 217, 99, 82, 235, 123, 100, 30, 128, 22, 149, 158, 207, 22, 223, 10, 100, 7, 185, 53, 10, 140, 216, 106, 8, 34, 88, 100, 7, 241, 187, 232, 68, 22, 69, 80, 91, 143, 218, 60, 87, 0, 2, 105, 167, 100, 130, 60, 61, 238, 146, 181, 207, 68, 227, 226, 87, 132, 125, 46, 120, 255, 199, 105, 187, 206, 24, 223, 73, 102, 113, 129, 225, 98, 168, 11, 89, 240, 94, 183, 150, 36, 214, 229, 15, 217, 224, 36, 239, 224, 175, 163, 136, 104, 190, 139, 16, 78, 215, 66, 185, 180, 175, 3, 92 },
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = new byte[] { 226, 90, 232, 54, 15, 6, 114, 129, 161, 32, 104, 61, 224, 76, 207, 152, 165, 105, 171, 13, 239, 211, 81, 105, 90, 14, 39, 48, 253, 63, 61, 22, 180, 147, 39, 138, 237, 101, 132, 180, 111, 162, 149, 115, 178, 219, 72, 166, 37, 97, 88, 226, 216, 71, 122, 196, 89, 198, 182, 162, 122, 193, 72, 237 },
                            PasswordSalt = new byte[] { 252, 5, 161, 178, 112, 65, 74, 254, 180, 194, 253, 132, 160, 134, 118, 228, 124, 233, 190, 240, 207, 75, 132, 6, 217, 99, 82, 235, 123, 100, 30, 128, 22, 149, 158, 207, 22, 223, 10, 100, 7, 185, 53, 10, 140, 216, 106, 8, 34, 88, 100, 7, 241, 187, 232, 68, 22, 69, 80, 91, 143, 218, 60, 87, 0, 2, 105, 167, 100, 130, 60, 61, 238, 146, 181, 207, 68, 227, 226, 87, 132, 125, 46, 120, 255, 199, 105, 187, 206, 24, 223, 73, 102, 113, 129, 225, 98, 168, 11, 89, 240, 94, 183, 150, 36, 214, 229, 15, 217, 224, 36, 239, 224, 175, 163, 136, 104, 190, 139, 16, 78, 215, 66, 185, 180, 175, 3, 92 },
                            Role = "Customer",
                            Username = "customer"
                        });
                });

            modelBuilder.Entity("Api.Models.Account", b =>
                {
                    b.HasOne("Api.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
